import React, { useState, useEffect, StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { HashRouter, Routes, Route } from 'react-router-dom';
import Quiz from './quiz';
import QuizCard from './quiz-card';

const App = () => {
  const [quizMetadata, setQuizMetadata] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const formatQuizMetadata = (dataList) => {
    let quizCardList = dataList.map((item, index) => {
      item.metadata.id = index + 1;
      return item.metadata;
    });
    return quizCardList;
  }


  const fetchData = async () => {
    try {
      const response = await fetch('/data/data.json');
      if (!response.ok) {
        throw new Error(`Failed to fetch data.json: ${response.status} ${response.statusText}`);
      }
      const data = await response.json();
      /**
       * Check if each item conforms to quizSchema : @see data-schema.js
       */
      if (Array.isArray(data)) {
        const validDataSchema = data.every(item =>
          typeof item.metadata.id === 'number' &&
          typeof item.metadata.categorie === 'string' &&
          typeof item.metadata.description === 'string'
        );

        if (validDataSchema) {
          localStorage.setItem('data', JSON.stringify(data));
          setQuizMetadata(formatQuizMetadata(data));
        } else {
          setError("Error: Data from data.json does not match the quizSchema .");
        }

      } else {
        setError("Error: Data from data.json is not an array.");
      }
    } catch (err) {
      setError(`Error loading data.json: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (quizMetadata) {
      setLoading(false);
    }
  }, [quizMetadata]);

  useEffect(() => {
    fetchData();
    // let storedData = localStorage.getItem('data');
    // if (!storedData) {
    //   // check data.metadata.date
    //   fetchData();
    // }
    // else{
    //   setQuizMetadata(formatQuizMetadata(JSON.parse(storedData)));
    // }
  }, []);

  const Home = () => {
    return (
      <>
        <header className="">
          <div className="collapse" id="navbarHeader">
            <div className="container">
              <div className="row">
                <div className="col-sm-8 col-md-7 py-4">
                  <h4>About</h4>
                  <p className="text-body-secondary">
                    This 10-question quiz, generated by an AI, serves as a concise tool for 
                    recalling information and boosting general knowledge.
                    Each question targets a distinct concept or fact within the chosen subject.
                    The quiz may also contain technical concepts at an intermediate and advanced level.
                    Please be aware that an AI, like humans, can make mistakes, 
                    so the information in the quiz should not be considered definitively correct.
                    If you find any errors, you are welcome to report them by making a pull 
                    request to GitHub page.                    
                  </p>
                </div>
                <div className="col-sm-4 offset-md-1 py-4">
                  <h4>Github</h4>
                  <ul className="list-unstyled">
                    <li><a href="https://github.com/cherattk/cherattk.github.io" target="blank" className="text-dark">Github page</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div className="navbar">
            <div className="container">
              <a href="/" className="navbar-brand d-flex align-items-center text-primary">
                <strong>(Brain)<sup>10</sup></strong>
              </a>
              <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span className="navbar-toggler-icon"></span>
              </button>
            </div>
          </div>
        </header>
        <main>
          <section className="py-5 text-center container">
            <div className="row">
              <div className="mx-auto">
                <h1 className="display-5 text-primary">
                  {/* <i className='bi bi-rocket text-danger me-3'></i> */}
                  10 Questions Brain Booster
                  <i className='bi bi-rocket text-danger ms-3'></i>
                </h1>
              </div>
            </div>
          </section>
          <div className="py-5">
            <div className="container">
              <div className="row row-cols-1 row-cols-sm-2 row-cols-md-3">
                {
                  quizMetadata.map((item, index) => {
                    return (<QuizCard key={"sub-c" + index} quizMetadata={item} />)
                  })
                }
              </div>
            </div>
          </div>
        </main>
        <footer className="text-body-secondary py-5">
          <div className="container">
          </div>
        </footer>
      </>
    )
  }

  if (loading) {
    return <div>Loading subjects...</div>;
  }

  if (error) {
    return <div>Error : {error}</div>;
  }

  return (
    <>
      <HashRouter>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/quiz/:quizId" element={<Quiz />} />
        </Routes>
      </HashRouter>
    </>
  );
};

const RootApp = createRoot(document.getElementById('app'));
RootApp.render(process.env.NODE_ENV === 'development' ? (
  <React.StrictMode>
    <App />
  </React.StrictMode>
) : (
  <App />
));
